version: '3.9'
services:
  dashboard:
    image: viettrann/vtrade:x86_64-latest
    ports:
      - 8050:8050
    depends_on:
      - processor
    network_mode: host

  processor:
    image: viettrann/str-proc:x86_64-latest
    ports:
      - 8000:8000
    network_mode: host