version: '3.9'
services:
  vtrade:
    image: viettrann/vtrade:x86_64
    ports:
      - 8050:8050
    depends_on:
      - strategy-processor
      - fundamental

  strategy-processor:
    image: viettrann/strategy-processor:x86_64
    environment:
      - TWEL_DATA_KEY=${TWEL_DATA_KEY}
    ports:
      - 8000:8000
  
  fundamental:
    image: viettrann/fundamental:x86_64
    ports:
      - 3000:3000